//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class First_Floor
    {
        public int ID { get; set; }
        public int Row { get; set; }
        public int Col { get; set; }
        public int Value { get; set; }
        public string Name { get; set; }
        public int PathOrNot { get; set; }
    }
}
