//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid02.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolNavDBEntities : DbContext
    {
        public SchoolNavDBEntities()
            : base("name=SchoolNavDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<First_Floor> First_Floor { get; set; }
        public virtual DbSet<Ground_Floor> Ground_Floor { get; set; }
        public virtual DbSet<Second_Floor> Second_Floor { get; set; }
        public virtual DbSet<Mapped_Floor> Mapped_Floor { get; set; }
    }
}
